# -*- coding: utf-8 -*-
"""
Programmatic SEO page definitions — service × industry combinations.
Each entry must include substantive industry-specific content (~600+ words).
Generic placeholder content gets de-ranked by Google helpful-content system.
"""

PAGES = []

# ═══════════════════════════════════════════════════════════════════
# 1. ERP for Textile Manufacturers
# ═══════════════════════════════════════════════════════════════════
PAGES.append({
    "slug": "erp-for-textile-manufacturers",
    "service_name": "ERP Software Development for Textile Manufacturers",
    "service_type": "Custom ERP for Textile Manufacturing",
    "title": "ERP for Textile Manufacturers in India | Lot Tracking, Shade Management — XServ Labs",
    "description": "Custom ERP built for Indian textile manufacturers — lot tracking by shade, fabric processing stages, multi-unit conversions, GST-ready invoicing. Built around how textile mills actually run.",
    "keywords": "erp for textile manufacturers, textile erp india, custom erp textile, fabric manufacturing software, shade lot tracking, textile mill software hyderabad, garment erp india",
    "crumb": "ERP for Textile Manufacturers",
    "eyebrow": "ERP for Textile Manufacturing",
    "h1": "ERP built for the way <em>textile mills</em> actually run.",
    "lede": "Off-the-shelf ERPs don't understand shade matching, processing stages, GSM variance, or the 14 unit conversions between bale, lot, beam, and metre. We've built ERPs for textile manufacturers across spinning, weaving, processing, and garment — so ours does.",
    "cta1": "Start a project",
    "cta2": "Read the ERP guide",
    "cta2_href": "/services/erp-software-development/",
    "stat1_num": "Shade-aware",
    "stat1_lbl": "Lot tracking native",
    "stat2_num": "FEFO",
    "stat2_lbl": "Aged stock management",
    "stat3_num": "GST",
    "stat3_lbl": "+ e-invoicing built-in",
    "stat4_num": "Multi-unit",
    "stat4_lbl": "Bale, lot, kg, mtr",
    "why_label": "Who this is for",
    "why_h2": "If you've outgrown <em>Tally + Excel</em> but SAP B1 quotes ₹70 lakh.",
    "why_intro": "Indian textile manufacturers sit in a specific gap. SaaS ERPs don't model shade tracking. SAP B1 implementations cost more than half your annual turnover. The middle ground — custom ERP that actually understands textile — is what we build.",
    "pain_points": [
        "Mills tracking lots, batches, and shade variants across multiple spreadsheets that nobody can reconcile at month-end",
        "Processing units that can't tie greige to finished fabric in the costing system, so margin is always estimated",
        "Garment units running cutting tickets manually because no ERP module handles size-colour-style matrices the way they need",
        "Spinning mills mixing pre-dyed cotton with mélange yarn and losing track of which lot ended up in which beam",
        "Owners who get quoted ₹70 lakh for SAP B1 and walk away — but need something more than Tally",
        "Teams holding the operations together with one experienced foreman who remembers everything in his head",
    ],
    "what_h2": "Built around <em>textile workflows</em>, not adapted from a generic ERP.",
    "what_intro": "Each module below was built because a real textile client needed it. None of it is a generic ERP module renamed for textile.",
    "capabilities": [
        ("Shade-aware lot tracking", "Track raw cotton, yarn, fabric by shade and lot. Match shades across batches. Flag mismatches before they hit the loom."),
        ("Process costing across stages", "Greige to finished fabric with stage-wise costing — sizing, dyeing, printing, finishing. Real-time WIP valuation, not month-end estimates."),
        ("Multi-unit conversions", "Bale to kg to lot to metre to piece, with conversion factors that vary by product. Done once, applied everywhere."),
        ("Size-colour-style matrices", "For garment units — track inventory and orders across SKU dimensions that off-the-shelf ERPs flatten into a single product code."),
        ("Job cards &amp; production tracking", "From cutting ticket through stitching, finishing, packing. With piece-rate worker payouts integrated."),
        ("Loom &amp; machine tracking", "Tie production to specific looms, mahcines, operators. Identify bottleneck machines from real data, not anecdote."),
    ],
    "approach_label": "How we approach textile ERP",
    "approach_h2": "Process-first. Software second.",
    "approach_left_h3": "Week one: shop-floor immersion",
    "approach_left_p": "We send our team to your mill. Watch the actual workflows. Map the spreadsheets, the WhatsApp groups, the registers. Identify the 3 modules that hurt most. The spec is written from observation, not from a feature checklist.",
    "approach_right_h3": "Sprints with weekly demos",
    "approach_right_p": "Two-week sprints. Working software every Friday. You see progress on the actual modules that matter — shade tracking, costing, job cards — not slides about hypothetical features. Most v1s ship in 14–20 weeks.",
    "chips_h2": "We have built ERPs for these textile <em>sub-sectors</em>.",
    "chips": ["Spinning mills", "Weaving units", "Knitting", "Dyeing &amp; processing", "Garment manufacturing", "Home textile", "Industrial textile", "Yarn trading", "Fabric processing", "Export units", "Embroidery", "Made-ups &amp; finishing"],
    "faq": [
        ("Does your ERP handle shade matching natively?", "Yes — it is a first-class concept in our textile ERP, not an afterthought. Every lot, batch, and material movement carries shade tracking. Mismatches get flagged at receipt, not after the loom has run for a shift."),
        ("Can it handle our specific costing method?", "Yes. We support standard costing, actual costing, job-based, and process-based costing — and you can mix methods across product lines. Most textile mills end up using process-based for processing units and job-based for garment units."),
        ("How long does a textile ERP build take?", "Focused v1 (3–4 modules covering your biggest pain): 14–18 weeks. Full multi-module enterprise rollout with mobile apps, integrations, and shop-floor IoT: 20–32 weeks, phased."),
        ("Will it integrate with our Tally and GST filings?", "Yes — bi-directional Tally sync, native GST invoicing, IRN generation via IRP, e-way bill APIs. You can keep Tally for accounts and use our ERP for operations, or migrate accounts over time. Your call."),
        ("Can we deploy on-premise?", "Yes. Many textile manufacturers prefer on-prem deployment for continuity. We support on-prem, your private cloud, or hosted in our managed cloud — same software."),
    ],
    "final_cta_h2": "Got a textile mill and ERP shopping is <em>painful</em>? Talk to us.",
    "final_cta_p": "30-minute call. We'll tell you honestly whether custom is the right answer or whether Zoho/SAP fits — we have recommended both before.",
    "cta_wa": "https://wa.me/918897599624?text=Hi%2C%20I%27d%20like%20to%20discuss%20ERP%20for%20a%20textile%20mill.",
    "related": [
        {"href": "/services/erp-software-development/", "ttl": "ERP Development", "desc": "The full custom ERP guide — process, modules, FAQ, pricing."},
        {"href": "/industries/manufacturing/", "ttl": "Manufacturing Software", "desc": "Custom ERP, MES, shop-floor, quality across all Indian manufacturing."},
        {"href": "/blog/cost-to-build-erp-in-india/", "ttl": "ERP cost in India (2026)", "desc": "Real pricing math for custom ERP vs SAP B1 vs Zoho."},
    ],
})

# ═══════════════════════════════════════════════════════════════════
# 2. ERP for Pharma Manufacturers
# ═══════════════════════════════════════════════════════════════════
PAGES.append({
    "slug": "erp-for-pharma-manufacturers",
    "service_name": "ERP Software Development for Pharma Manufacturers",
    "service_type": "Custom Pharma ERP with 21 CFR Part 11 Compliance",
    "title": "ERP for Pharma Manufacturers in India | 21 CFR, Batch Traceability, Schedule M — XServ Labs",
    "description": "Custom ERP built for Indian pharma manufacturers — batch traceability, FEFO, 21 CFR Part 11 audit trails, Schedule M compliance, electronic signatures. Built for regulators, not slides.",
    "keywords": "erp for pharma manufacturers, pharma erp india, 21 cfr compliant erp, schedule m software, batch traceability pharma, fefo pharma erp, gmp compliant software india",
    "crumb": "ERP for Pharma Manufacturers",
    "eyebrow": "ERP for Pharma Manufacturing",
    "h1": "ERP for pharma — built to <em>pass audits</em>, not just demos.",
    "lede": "Pharma manufacturing has a higher bar than most ERP categories. 21 CFR Part 11. Schedule M. Batch traceability that survives a regulator's inspection. FEFO and shelf-life management without manual workarounds. We've built ERPs that hold up to all of it.",
    "cta1": "Start a project",
    "cta2": "Read the ERP guide",
    "cta2_href": "/services/erp-software-development/",
    "stat1_num": "21 CFR",
    "stat1_lbl": "Part 11 ready",
    "stat2_num": "FEFO",
    "stat2_lbl": "+ shelf-life native",
    "stat3_num": "On-prem",
    "stat3_lbl": "When compliance demands",
    "stat4_num": "Sched M",
    "stat4_lbl": "Workflow-aware",
    "why_label": "Who this is for",
    "why_h2": "Built for pharma businesses where the regulator is the <em>real customer</em>.",
    "why_intro": "Pharma ERP isn't a SaaS subscription decision. It's an audit-defence decision. The wrong system creates regulatory exposure that takes years to clean up. The right system passes inspections without your QA head losing a weekend.",
    "pain_points": [
        "Manufacturers running CDSCO / WHO-GMP / EU-GMP audits with ERP audit trails that the inspector picks apart",
        "Distributors mixing batches at the warehouse without traceability — and discovering it during a recall investigation",
        "QC teams maintaining BMR/BPR in PDF templates that production updates by hand at end of shift",
        "Companies still using Tally + Excel for batch tracking, hoping nothing gets recalled",
        "Owners who tried SAP B1 pharma vertical and bounced off the implementation cost and timeline",
        "Production planners working from yesterday's data because the ERP doesn't have real-time WIP visibility",
    ],
    "what_h2": "Modules built for <em>pharma operations</em>, not adapted from general manufacturing.",
    "what_intro": "Every module below has been deployed in real Indian pharma operations and survived audit scrutiny. Generic ERPs sold to pharma typically need ₹20L+ of customisation to reach this level.",
    "capabilities": [
        ("Batch &amp; lot traceability", "Every material movement tied to batch and lot. Forward and backward traceability: given a finished batch, trace to every raw material lot; given a raw material lot, find every finished batch it touched."),
        ("21 CFR Part 11 audit trails", "Immutable audit logs. Electronic signatures with secondary authentication. User action logging. Time-stamped and tamper-evident — meets US-FDA expectations."),
        ("BMR / BPR digitisation", "Batch manufacturing and batch packing records native in the system. Configurable per product. Approval workflows. No more paper templates floating between QA and production."),
        ("FEFO inventory &amp; expiry alerts", "First-expiry-first-out at every stock issue. Configurable shelf-life by product. Alerts well before expiry hits operational risk."),
        ("Quality control workflows", "In-process checks, raw-material release, finished-goods QC, COA generation, deviation handling, OOS investigation tracking — built into operations, not a parallel system."),
        ("Recall management", "Trace forward from a batch in seconds. Generate recall lists by customer, lot, and channel. Audit the recall response after."),
    ],
    "approach_label": "How we approach pharma ERP",
    "approach_h2": "Validation-first. Speed second.",
    "approach_left_h3": "GMP-aligned development",
    "approach_left_p": "Pharma ERP isn't built with the same shortcuts as regular SaaS. We work to GAMP 5 principles — risk-based validation, design qualification, installation qualification, operational qualification. Test scripts mapped to user requirements. Documentation that supports audit defence.",
    "approach_right_h3": "On-prem when needed",
    "approach_right_p": "Many of our pharma clients require fully on-prem deployment for compliance and data sovereignty. We support that — our pharma ERP runs on-prem, in your private cloud, or air-gapped if your regulator requires. Same software, your control.",
    "chips_h2": "We have built pharma ERPs for these sub-sectors.",
    "chips": ["Formulations", "API manufacturing", "Nutraceuticals", "Veterinary pharma", "Cosmetics", "Medical devices", "Contract manufacturing", "Pharma distribution", "Bulk drug", "Generics", "Herbal &amp; ayurveda", "Pharma logistics"],
    "faq": [
        ("Is your pharma ERP 21 CFR Part 11 compliant?", "Yes — immutable audit trails, electronic signatures with secondary authentication, user action logging, time-stamped and tamper-evident records. We provide validation documentation to support FDA, EU-GMP, and CDSCO inspections."),
        ("Can the ERP be deployed on-premise?", "Yes — many pharma clients require on-prem deployment for compliance, data sovereignty, or audit reasons. We support fully on-prem, hybrid, your private cloud, or air-gapped deployments."),
        ("How long does pharma ERP implementation take?", "Typically 20–32 weeks for a comprehensive deployment with validation. Smaller scope (e.g. just batch traceability + QC) can be live in 14–18 weeks. Full multi-site rollouts with validation documentation can run 6–9 months."),
        ("Do you handle CDSCO and WHO-GMP audit preparation?", "Yes — our ERP comes with validation documentation packs, audit trail reports, and electronic signature workflows that auditors expect to see. We have supported clients through CDSCO, WHO-GMP, EU-GMP, and US-FDA inspections."),
        ("Will it integrate with our existing systems?", "Yes — bi-directional integration with Tally, SAP, Oracle, Bizom, LIMS systems (LabWare, STARLIMS), and weighing-scale/PLC/SCADA on the production floor. Integration scope is part of the discovery phase."),
    ],
    "final_cta_h2": "Need pharma ERP that <em>holds up to inspection</em>?",
    "final_cta_p": "30-minute scoping call. We will tell you honestly whether your current ERP can be patched up or whether a rebuild is the lower-risk path.",
    "cta_wa": "https://wa.me/918897599624?text=Hi%2C%20I%27d%20like%20to%20discuss%20ERP%20for%20a%20pharma%20company.",
    "related": [
        {"href": "/services/erp-software-development/", "ttl": "ERP Development", "desc": "The full custom ERP guide — process, modules, FAQ, pricing."},
        {"href": "/industries/healthcare/", "ttl": "Healthcare Software", "desc": "HMS, EMR, telehealth, lab, pharma — full healthcare practice."},
        {"href": "/services/cybersecurity/", "ttl": "Cybersecurity", "desc": "Validation, security, and compliance for regulated pharma systems."},
    ],
})

# ═══════════════════════════════════════════════════════════════════
# 3. ERP for Distribution & Wholesale
# ═══════════════════════════════════════════════════════════════════
PAGES.append({
    "slug": "erp-for-distribution-wholesale",
    "service_name": "ERP Software Development for Distribution and Wholesale",
    "service_type": "Custom ERP for Distribution Businesses",
    "title": "ERP for Distribution &amp; Wholesale Businesses in India — XServ Labs",
    "description": "Custom ERP built for Indian distribution and wholesale operations. Multi-warehouse, multi-channel, route accounting, secondary sales, scheme management, GST and e-way bill native.",
    "keywords": "erp for distribution wholesale, distribution erp india, wholesale software india, secondary sales software, scheme management software, multi warehouse erp",
    "crumb": "ERP for Distribution &amp; Wholesale",
    "eyebrow": "ERP for Distribution",
    "h1": "ERP for distributors and wholesalers — built for the way <em>secondary sales</em> actually run.",
    "lede": "Distribution operations live and die on stock turn, scheme accuracy, and route productivity. Generic ERPs handle warehouses but miss the nuances — route accounting, beat-wise targets, sub-stockist allocation, scheme cost reconciliation. We build the ones that get it right.",
    "cta1": "Start a project",
    "cta2": "Read the ERP guide",
    "cta2_href": "/services/erp-software-development/",
    "stat1_num": "Multi-WH",
    "stat1_lbl": "+ multi-state native",
    "stat2_num": "Routes",
    "stat2_lbl": "&amp; beat-wise targets",
    "stat3_num": "Schemes",
    "stat3_lbl": "Cost-reconciled",
    "stat4_num": "Mobile",
    "stat4_lbl": "For sales reps",
    "why_label": "Who this is for",
    "why_h2": "If your distribution business has <em>outgrown</em> Bizom + Tally.",
    "why_intro": "Distribution and wholesale businesses in India share a specific pain. The off-the-shelf tools (Bizom, FMCG-focused SFAs) handle the field side. Tally handles accounts. Nothing handles the messy middle — scheme reconciliation, sub-stockist allocation, route economics, returns, slow-mover identification.",
    "pain_points": [
        "Distributors paying scheme costs they can't reconcile to actual secondary sales",
        "Beat-wise sales targets tracked in Excel because the SFA tool doesn't tie to inventory truth",
        "Multi-warehouse operations where dispatch decisions are made on yesterday's stock report",
        "Sub-stockist allocation that requires three people across two tools to compute",
        "Returns processing that takes a week and creates margin leakage nobody can explain",
        "Owners who can see the rupees moving but can't tell which beat or which SKU is profitable",
    ],
    "what_h2": "Modules built for <em>distribution economics</em>, not generic warehousing.",
    "what_intro": "Distribution ERPs sold in India typically force you into a generic warehouse + sales structure. Ours encodes the actual operating model — beats, routes, schemes, sub-stockists, secondary sales.",
    "capabilities": [
        ("Route &amp; beat management", "Beat-wise sales targets, route productivity reports, salesman daily plans, and live tracking via mobile apps. Sales rep app integrated, not a separate tool."),
        ("Scheme &amp; promotion management", "Configure schemes by product, channel, period. System computes scheme cost against actual sales. Auto-reconcile claims from FMCG principals."),
        ("Multi-warehouse with real-time truth", "Stock visibility across warehouses, branches, sub-stockists, vans. Dispatch decisions made on live data, not yesterday's report."),
        ("Sub-stockist allocation", "Allocation rules by product, channel, geography. Automated allocation runs. Manual override with audit trail when business requires."),
        ("Returns &amp; CN/DN workflows", "Returns processed in minutes, not days. Credit notes auto-generated. Margin leakage from returns made visible per product, customer, route."),
        ("GST + e-way bill native", "GST invoicing, IRN generation, e-way bill API, place-of-supply correct, RCM handled. For distribution this is non-negotiable."),
    ],
    "approach_label": "How we approach distribution ERP",
    "approach_h2": "Field-first, back-office <em>integrated</em>.",
    "approach_left_h3": "Start with the field workflow",
    "approach_left_p": "The biggest leakage in distribution is between field operations and back-office. We start every project by spending a day with sales reps on their actual beats, then design back from that reality — not from a pre-built SFA template.",
    "approach_right_h3": "Mobile + web as one system",
    "approach_right_p": "Sales rep mobile apps and back-office web are one platform, not separate tools synced over an API. Real-time stock visibility on the rep's phone. Real-time order visibility on the manager's dashboard. No reconciliation drift.",
    "chips_h2": "Sub-sectors we have shipped for.",
    "chips": ["FMCG distribution", "Pharma distribution", "Electronics &amp; appliances", "Building materials", "Auto parts", "Textile &amp; apparel wholesale", "Food &amp; beverage", "Beauty &amp; cosmetics", "Chemicals &amp; industrial", "Stationery &amp; office supplies", "Cement &amp; bulk", "Agri inputs"],
    "faq": [
        ("Can your ERP handle our scheme structure?", "Yes — schemes by product, channel, period, with quantity and percentage variants, slabs, multi-tier discounts. We have shipped scheme engines for FMCG distributors that compute against millions of secondary sales transactions monthly."),
        ("Does it work for multi-state operations?", "Yes — multi-warehouse, multi-state, multi-branch, multi-GSTIN. Inter-state stock transfers with auto-generated e-way bills. Place-of-supply rules applied correctly."),
        ("Will the sales rep app work offline?", "Yes — offline-first by design. Reps can take orders, capture POD, see catalogue, and sync when reception comes back. Built and tested on Indian rural beat conditions."),
        ("Can we integrate with FMCG principal systems?", "Yes — most major FMCG principals provide API or SFTP-based integration for primary order receipts and secondary sales submission. We have built integrations with HUL, ITC, Nestle, P&amp;G, and others."),
        ("What about existing Bizom / Field Assist deployments?", "We can replace, integrate with, or extend Bizom and similar SFAs. Honest read: if your team is happy with Bizom for the field side, integration is faster than replacement. If you are migrating because of fundamental gaps, replacement is the lower-risk path."),
    ],
    "final_cta_h2": "Distribution business and your tools <em>are not talking</em>?",
    "final_cta_p": "30-minute call. We will tell you honestly whether you need a full ERP, a smart integration layer, or just better workflow design on what you already have.",
    "cta_wa": "https://wa.me/918897599624?text=Hi%2C%20I%27d%20like%20to%20discuss%20ERP%20for%20a%20distribution%20business.",
    "related": [
        {"href": "/services/erp-software-development/", "ttl": "ERP Development", "desc": "Custom ERP guide — process, modules, pricing."},
        {"href": "/industries/logistics/", "ttl": "Logistics Software", "desc": "Fleet, TMS, warehouse, last-mile platforms."},
        {"href": "/products/traxium/", "ttl": "Traxium", "desc": "Our AI fleet manager — for the trucking side of your distribution."},
    ],
})

# ═══════════════════════════════════════════════════════════════════
# 4. Custom Software for Healthcare
# ═══════════════════════════════════════════════════════════════════
PAGES.append({
    "slug": "custom-software-for-healthcare",
    "service_name": "Custom Software Development for Healthcare",
    "service_type": "Bespoke Healthcare Software Engineering",
    "title": "Custom Software Development for Healthcare in India — HMS, EMR, Telehealth — XServ Labs",
    "description": "Custom software for Indian hospitals, clinics, diagnostic labs, and pharma. HMS extensions, EMR customisations, telehealth platforms, lab integrations, ABDM-ready, HIPAA-aware, on-prem capable.",
    "keywords": "custom healthcare software india, hospital software development hyderabad, custom hms development, emr customisation india, telehealth platform development, healthcare integration india",
    "crumb": "Custom Software for Healthcare",
    "eyebrow": "Custom Software · Healthcare",
    "h1": "Healthcare software <em>built around clinical workflow</em>, not flattened to fit one.",
    "lede": "Off-the-shelf HMS handles 70% of what most hospitals need. Custom software handles the other 30% — your specific workflow, your specialty, your integration with existing diagnostic, pharmacy, and billing systems. That is where most healthcare IT pain lives.",
    "cta1": "Start a project",
    "cta2": "Read the healthcare guide",
    "cta2_href": "/industries/healthcare/",
    "stat1_num": "ABDM",
    "stat1_lbl": "Ready integration",
    "stat2_num": "FHIR",
    "stat2_lbl": "+ HL7 v2 day one",
    "stat3_num": "On-prem",
    "stat3_lbl": "When required",
    "stat4_num": "DPDP",
    "stat4_lbl": "Compliant by design",
    "why_label": "Who this is for",
    "why_h2": "For healthcare teams whose <em>workflows</em> never fit the boxes.",
    "why_intro": "Healthcare software is uniquely workflow-dense. Every specialty has its own assessment forms, its own protocols, its own follow-up rhythms. Generic HMS systems flatten these into a common template. Custom software encodes the actual workflow your clinicians use.",
    "pain_points": [
        "Hospitals where consultants insist on paper notes because the HMS workflow does not match their specialty assessment",
        "Diagnostic chains running multi-format reports across pathology, radiology, cardiology with no unified result delivery",
        "Telehealth startups whose video consultation flow needs to integrate with their HMS, EMR, lab, and payments",
        "Pharma supply chains needing batch tracking integration that off-the-shelf hospital systems won't bend to",
        "Insurance / TPA workflows that take 4 days because the integration with payer systems is manual",
        "Clinics that have built their differentiation on a specific protocol that no off-the-shelf system encodes",
    ],
    "what_h2": "Built around <em>clinical reality</em>, not consultant slide decks.",
    "what_intro": "We have built healthcare software for hospital chains, specialty clinics, diagnostic networks, telehealth platforms, and pharma manufacturers. The pattern: start from the clinician's screen, work backward to the data model.",
    "capabilities": [
        ("Specialty-specific EMR modules", "Cardiology, ortho, gynae, paeds, ICU, oncology — each with their own templates, protocols, and reporting structures. Built by talking to clinicians, not generic forms generators."),
        ("ABDM-ready integrations", "ABHA ID linkage, HIE-CM consent flows, FHIR R4 interoperability, HFR/HPR registration. Built so your patients can carry their records, your hospital stays compliant."),
        ("Telehealth platforms", "Video consults, e-prescriptions, scheduling, payments, follow-up reminders. Built on WebRTC, Zoom, Daily.co — picked by use case. Works on patient phones, not just laptops."),
        ("Lab &amp; diagnostic integration", "LIS integration (LabWare, STARLIMS, custom), instrument middleware (Mindray, Siemens, Roche analysers), centralised result delivery."),
        ("Patient and doctor apps", "Native iOS and Android. Appointments, results, prescriptions, video calls, in-app payment. Offline support where it matters."),
        ("Insurance / TPA workflows", "Pre-auth, claim submission, status tracking, settlement reconciliation. Integration with Vidal, MedSave, Health India, and major TPA systems."),
    ],
    "approach_label": "How we approach healthcare software",
    "approach_h2": "Clinician-led design. <em>Always.</em>",
    "approach_left_h3": "Shadow before you design",
    "approach_left_p": "Every healthcare project starts with us shadowing the actual clinicians and staff who will use the system. We watch what they do, where they get stuck, where they have built workarounds. The spec comes from observation, not from a feature list.",
    "approach_right_h3": "Compliance from day one",
    "approach_right_p": "DPDP Act, ABDM standards, HIPAA-aware data handling, HL7 / FHIR interoperability — built into the architecture from the start. Retrofitting compliance into a healthcare system is significantly more expensive than designing for it.",
    "chips_h2": "Healthcare sub-sectors we have shipped for.",
    "chips": ["Multi-specialty hospitals", "Specialty clinics", "Diagnostic chains", "Telehealth platforms", "Wellness &amp; fitness apps", "Dental chains", "Eye care chains", "Home healthcare", "Eldercare", "Pharma manufacturers", "Insurance / TPA", "Medical devices"],
    "faq": [
        ("Can you customise our existing HMS, or do you only build new?", "Both — custom modules on existing HMS (Insta, Suvarna, eHospital, custom), or fully new. Usually we start with extending what works and rebuild only where the existing system fundamentally cannot support a new workflow."),
        ("Are your systems ABDM compliant?", "Yes — we have built ABDM-ready integrations: ABHA ID linkage, HIE-CM consent management, FHIR R4 interoperability, HFR/HPR linkage. Our team has worked through NDHM milestone certifications with hospital clients."),
        ("Can your healthcare software run on-premise?", "Yes — many hospital clients require on-prem deployment for compliance, data sovereignty, and continuity. We support fully on-prem, hybrid, your private cloud (AWS / Azure / GCP India regions), or hosted in our managed cloud."),
        ("How do you handle patient data privacy?", "DPDP Act compliance, HIPAA-aware data handling, encryption at rest and in transit, role-based access, immutable audit trails. We sign DPAs and custom security agreements as standard for healthcare engagements."),
        ("What about integration with our existing lab and pharmacy systems?", "Yes — we have integrated with major LIS systems (LabWare, STARLIMS), pharmacy management systems, instrument middleware, and Indian-market TPA systems. Most healthcare projects involve 5–15 integrations; that is normal."),
    ],
    "final_cta_h2": "Healthcare software pain you cannot fix in your current HMS?",
    "final_cta_p": "30-minute call. We will tell you honestly whether you need extension, replacement, or just better integration between what you already have.",
    "cta_wa": "https://wa.me/918897599624?text=Hi%2C%20I%27d%20like%20to%20discuss%20custom%20healthcare%20software.",
    "related": [
        {"href": "/industries/healthcare/", "ttl": "Healthcare Software", "desc": "HMS, EMR, telehealth, lab, pharma — the full healthcare practice."},
        {"href": "/services/custom-software-development/", "ttl": "Custom Software", "desc": "Bespoke software development — broader services guide."},
        {"href": "/services/mobile-app-development/", "ttl": "Mobile App Development", "desc": "Patient apps, doctor apps, field worker apps — native or cross-platform."},
    ],
})

# ═══════════════════════════════════════════════════════════════════
# 5. Mobile App for D2C Brands
# ═══════════════════════════════════════════════════════════════════
PAGES.append({
    "slug": "mobile-app-for-d2c-brands",
    "service_name": "Mobile App Development for D2C Brands",
    "service_type": "iOS and Android App Development for Indian D2C Brands",
    "title": "Mobile App Development for D2C Brands in India — Native, React Native, Flutter — XServ Labs",
    "description": "Mobile app development for Indian D2C brands. Native iOS / Android, React Native, Flutter — built around Shopify or custom backends, with loyalty, subscription, payments, and personalization that actually convert.",
    "keywords": "mobile app for d2c brands india, d2c mobile app development, shopify mobile app builder, custom d2c app, native ecommerce app india, react native ecommerce india",
    "crumb": "Mobile App for D2C Brands",
    "eyebrow": "Mobile · D2C",
    "h1": "D2C apps that <em>actually drive</em> repeat orders.",
    "lede": "Most D2C mobile apps are a thin wrapper on the website. They get downloads, see one purchase, get uninstalled. The apps that actually drive retention have specific patterns — loyalty, subscription flow, personalised home, push that respects the user. We build those.",
    "cta1": "Start a project",
    "cta2": "Read the mobile guide",
    "cta2_href": "/services/mobile-app-development/",
    "stat1_num": "iOS",
    "stat1_lbl": "+ Android always",
    "stat2_num": "8–14w",
    "stat2_lbl": "Typical MVP",
    "stat3_num": "Native",
    "stat3_lbl": "or RN/Flutter — picked by fit",
    "stat4_num": "App Store",
    "stat4_lbl": "Submission included",
    "why_label": "Who this is for",
    "why_h2": "D2C brands ready to <em>move beyond</em> the auto-generated wrapper app.",
    "why_intro": "Shopify Mobile, custom-wrapped PWAs, white-label app builders — they all hit a ceiling around 5% of users. The retention play needs a real native app with the patterns that drive habit, not a brochureware screenshot.",
    "pain_points": [
        "D2C brands with 50% repeat-purchase potential losing it because their app is a website in a frame",
        "Subscription brands whose churn is driven by friction in skip-or-swap flows that the website handles awkwardly",
        "Brands shipping push notifications that get muted by week 2 because the targeting is naive",
        "Loyalty programs that exist on the backend but have no surface in the app",
        "Apps with conversion rates 30% lower than web because the checkout flow was never optimised for mobile",
        "Brands wanting to launch subscription, referral, or in-app-only SKUs but their app builder doesn't support it",
    ],
    "what_h2": "D2C app patterns that <em>actually move metrics</em>.",
    "what_intro": "We have built D2C apps across apparel, beauty, food, wellness, and home categories. The patterns below are what we know works — not the feature lists app builders advertise.",
    "capabilities": [
        ("Personalised home", "Algorithmic home screen — recently viewed, recommended based on profile, daily-deal blocks. Built on top of your existing Shopify catalog or custom backend."),
        ("Subscription &amp; auto-replenish flows", "Skip, swap, pause, modify — all in 2 taps. Real subscription billing integration (Razorpay subscriptions, Stripe, custom). Built so subscribers actually stay."),
        ("Loyalty &amp; gamification", "Points, tiers, streaks, exclusive drops, reward redemption. Native UX, not webview. Integration with your CRM and order data."),
        ("In-app payment optimisation", "Native Razorpay / PhonePe / GPay / Apple Pay / Google Pay flows. UPI Intent. One-tap repeat purchase. Conversion uplift typically 15–30% over wrapper apps."),
        ("Smart push notifications", "Behavioural triggers, not blast. Skip when it would be the wrong moment. Deep-link into the right product, not the home screen. Built with CleverTap, MoEngage, or OneSignal."),
        ("Shopify or custom backend", "Built on top of your existing Shopify store, or with a custom backend if you have outgrown Shopify. Same engineering team for both — no integration handoff."),
    ],
    "approach_label": "How we approach D2C apps",
    "approach_h2": "Built for the user who <em>opens it again</em>.",
    "approach_left_h3": "Retention-first design",
    "approach_left_p": "Most apps optimise for the first purchase. We design for the third. That changes the patterns — what surfaces on the home screen, how reorder works, how push notifications get used, what loyalty looks like. The first-order flow is solved; the retention flow is where projects live or die.",
    "approach_right_h3": "Performance and UX details",
    "approach_right_p": "60 fps scrolling. Sub-2-second cold start. Lazy image loading. Offline cart. App Store screenshots that actually convert. We obsess over the details that mobile users feel even if they can't articulate them.",
    "chips_h2": "D2C categories we have built for.",
    "chips": ["Apparel &amp; fashion", "Beauty &amp; personal care", "Food &amp; beverage", "Wellness &amp; supplements", "Home &amp; furniture", "Jewellery", "Pet products", "Mom &amp; baby", "Sustainable / eco brands", "Subscription boxes", "Snacking &amp; FMCG D2C", "Specialty foods"],
    "faq": [
        ("React Native or Native — which one for our D2C brand?", "Default: React Native or Flutter for most D2C brands — faster to ship, easier to maintain, performance is excellent for typical e-commerce flows. Go native (Swift/Kotlin) if you need heavy animations, AR try-on, complex camera features, or absolute performance for a flagship app."),
        ("Can you build on top of our existing Shopify store?", "Yes — common pattern. We build native apps on top of Shopify Storefront API, with extensions for loyalty, subscription, personalization where Shopify's mobile app doesn't reach. Bi-directional sync, native checkout, native payments."),
        ("How long does a D2C app take?", "MVP (8–15 screens, basic catalog + checkout): 8–12 weeks. Full D2C app with subscription, loyalty, personalization, push, and analytics: 14–20 weeks. App Store and Play Store submission is included; budget 1–3 weeks for review."),
        ("Do you handle App Store / Play Store submission?", "Yes — listing setup, screenshots, ASO basics, submission, rejection-and-resubmission handling, post-launch ratings response. We have shipped to both stores hundreds of times and know what gets flagged."),
        ("What about Apple Pay and UPI integration?", "Yes — native Apple Pay and Google Pay flows on iOS / Android. UPI Intent integration for the India market. Razorpay, PhonePe, PayU, Cashfree — picked by your existing payment stack."),
    ],
    "final_cta_h2": "D2C app that <em>drives</em> repeat orders, not just downloads.",
    "final_cta_p": "30-minute call. We will tell you whether you need a fresh native app, an upgrade to your current one, or some smart additions to push retention numbers.",
    "cta_wa": "https://wa.me/918897599624?text=Hi%2C%20I%27d%20like%20to%20discuss%20a%20D2C%20mobile%20app.",
    "related": [
        {"href": "/services/mobile-app-development/", "ttl": "Mobile App Development", "desc": "The full mobile app guide — native, cross-platform, process, pricing."},
        {"href": "/industries/retail/", "ttl": "Retail &amp; E-commerce", "desc": "POS, OMS, D2C platforms, omnichannel."},
        {"href": "/services/custom-software-development/", "ttl": "Custom Software", "desc": "Backend and admin platforms for your D2C operations."},
    ],
})

# ═══════════════════════════════════════════════════════════════════
# 6. Mobile App for Field Sales Teams
# ═══════════════════════════════════════════════════════════════════
PAGES.append({
    "slug": "mobile-app-for-field-sales-teams",
    "service_name": "Mobile App Development for Field Sales Teams",
    "service_type": "iOS and Android App Development for Field Sales Operations",
    "title": "Mobile App for Field Sales Teams in India — Offline-First SFA — XServ Labs",
    "description": "Custom mobile apps for Indian field sales teams. Offline-first, GPS tracking, order capture, beat planning, target tracking, real-time stock visibility. Built for the conditions Indian reps actually work in.",
    "keywords": "mobile app for field sales teams india, sfa app development india, sales force automation app, field sales app, beat planning app, offline first sales app india",
    "crumb": "Mobile App for Field Sales",
    "eyebrow": "Mobile · Field Sales",
    "h1": "Field sales apps built for the way Indian <em>reps actually work</em>.",
    "lede": "Patchy signal in tier-3 cities. Hot phones in Chennai summer. Battery dying by 4pm on a long beat. Reps using one hand while the other holds a sample catalog. Apps that don't handle these realities get uninstalled in week 2. We build the ones that survive.",
    "cta1": "Start a project",
    "cta2": "Read the mobile guide",
    "cta2_href": "/services/mobile-app-development/",
    "stat1_num": "Offline",
    "stat1_lbl": "First, always",
    "stat2_num": "10–14w",
    "stat2_lbl": "Typical MVP",
    "stat3_num": "GPS",
    "stat3_lbl": "+ battery-aware",
    "stat4_num": "Multi-lang",
    "stat4_lbl": "Where needed",
    "why_label": "Who this is for",
    "why_h2": "If your current SFA was built for a <em>9-to-5 office worker</em>, this is for you.",
    "why_intro": "Off-the-shelf SFA tools work for sales reps who have wifi, full batteries, and one hand free. Indian field sales doesn't always have those. Custom field apps respect those constraints by design — offline-first, battery-efficient, single-hand-friendly UI.",
    "pain_points": [
        "Reps abandoning the SFA app because it doesn't work in basement warehouses or rural beats",
        "Orders submitted late because the app requires network to save, and the network was patchy at the right moment",
        "Battery drain at 30% by 1pm because the app polls GPS constantly even when stationary",
        "Beat plans rigid in the app while real-world routes flex daily — reps gaming the system to make it match reality",
        "Real-time stock data nowhere visible — reps quoting from old printed catalogues",
        "Manager dashboards that show 'reps in field' but not 'orders captured' or 'shelf gaps reported'",
    ],
    "what_h2": "Patterns built for the <em>actual conditions</em> of Indian field sales.",
    "what_intro": "We have shipped field apps for FMCG distributors, pharma companies, B2B sales teams, technician dispatch, surveyors, and field agents. The patterns below are what we know works — not what looks good in a demo.",
    "capabilities": [
        ("Offline-first architecture", "Full app functionality without network. Local database with conflict-resolved sync. Order capture, beat completion, photo upload — all queue locally, sync when connection returns."),
        ("Battery-aware GPS", "Polls GPS intelligently — every few seconds when moving, every few minutes when stationary, never constantly. Geofence triggers without GPS-on-all-day cost."),
        ("Live stock visibility", "Real-time stock from your ERP or warehouse system — by SKU, by warehouse, by branch. Reps see what they can actually sell, not yesterday's printed catalogue."),
        ("Beat planning &amp; productivity", "Beat assignment, route optimisation, daily plan, productivity reporting. Reps see their beat for the day; managers see beat-vs-actual analytics."),
        ("Order capture with smart catalog", "Tap-to-order from catalog, search, recent orders, scheme applicability shown inline, GST and discount auto-computed. Submit in 30 seconds, not 3 minutes."),
        ("Photo capture &amp; shelf audits", "Shelf photos, competitive intel capture, damaged-stock reporting, merchandise compliance. Geotagged, time-stamped, compressed before upload."),
    ],
    "approach_label": "How we approach field sales apps",
    "approach_h2": "Ride along, then design.",
    "approach_left_h3": "A day in the beat",
    "approach_left_p": "Every field-app project starts with us spending a day with one of your sales reps on an actual beat. We watch what works, where they struggle, where they have built workarounds. That observation drives the design more than any product manager workshop could.",
    "approach_right_h3": "Test in real conditions",
    "approach_right_p": "We test on the actual devices your reps use (mid-tier Android, not iPhones), in the actual signal conditions of your beats (tier-3 cities, basement warehouses), under the actual battery pressure (10am to 7pm on one charge). If it fails in test, it would fail in production.",
    "chips_h2": "Field sales contexts we have shipped for.",
    "chips": ["FMCG distribution", "Pharma reps", "B2B industrial sales", "Insurance agents", "Real estate brokers", "Loan / credit officers", "Field technicians", "Survey teams", "Auditors", "Tax / accounting reps", "Construction supervisors", "Logistics field staff"],
    "faq": [
        ("Will the app work without internet?", "Yes — offline-first is the default architecture for our field apps. Reps can take orders, complete beats, capture photos, do everything they normally do — and the app syncs when network returns. With conflict resolution if data was updated server-side meanwhile."),
        ("What devices do you build for?", "We test on the actual devices Indian field reps use — typically mid-tier Android (Redmi, Realme, Vivo) running Android 10+ with 4 GB RAM. We support iOS too but most field teams in India are Android-first. Hardware-rugged devices (Zebra, Honeywell) when warehouse operations need them."),
        ("Can you integrate with our existing CRM / ERP?", "Yes — typical integrations include Salesforce, Zoho CRM, SAP, Oracle, custom ERPs, Tally. Bi-directional sync of customers, orders, stock, schemes, targets. Integration is part of every project scope."),
        ("How long does a field sales app take to build?", "MVP (basic beat plan + order capture + reporting): 8–12 weeks. Full app with offline, GPS, photo workflows, scheme engine, manager dashboards: 14–20 weeks. Pilot first with one branch before fleet rollout."),
        ("What about manager dashboards?", "Real-time view of beat completion, order capture, productivity, shelf-gap reports, photo audit trails. Web-based dashboard, mobile-responsive for field managers. Configurable per role — sales head sees totals, regional manager sees their region, ASM sees their team."),
    ],
    "final_cta_h2": "Field sales team using a tool that <em>doesn't fit</em> Indian field reality?",
    "final_cta_p": "30-minute call. We will tell you honestly whether your current tool can be patched, or whether building something fit-for-purpose is the lower-cost path.",
    "cta_wa": "https://wa.me/918897599624?text=Hi%2C%20I%27d%20like%20to%20discuss%20a%20field%20sales%20mobile%20app.",
    "related": [
        {"href": "/services/mobile-app-development/", "ttl": "Mobile App Development", "desc": "The full mobile app guide — native, cross-platform, process."},
        {"href": "/services/erp-software-development/", "ttl": "ERP Development", "desc": "The back-office system the field app feeds into."},
        {"href": "/services/erp-for-distribution-wholesale/", "ttl": "ERP for Distribution", "desc": "When the field app needs to plug into a distribution ERP we also build."},
    ],
})

# ═══════════════════════════════════════════════════════════════════
# 7. AI for Retail & Warehouse CCTV
# ═══════════════════════════════════════════════════════════════════
PAGES.append({
    "slug": "ai-for-retail-warehouse-cctv",
    "service_name": "AI on CCTV for Retail and Warehouse Operations",
    "service_type": "Computer Vision and AI for Retail and Warehouse CCTV",
    "title": "AI on Retail &amp; Warehouse CCTV — Shelf, Footfall, PPE, Headcount — XServ Labs",
    "description": "Computer vision and AI running on existing retail and warehouse CCTV — shelf monitoring, footfall, PPE compliance, headcount, queue alerts. On-prem processing. Built for Indian operations.",
    "keywords": "ai for retail cctv india, ai for warehouse cctv, computer vision retail india, shelf monitoring ai, footfall analytics india, ai workforce intelligence",
    "crumb": "AI for Retail &amp; Warehouse CCTV",
    "eyebrow": "AI · Retail &amp; Warehouse",
    "h1": "Turn the CCTV you <em>already paid for</em> into operational AI.",
    "lede": "Retail and warehouse operations sit on massive untapped CCTV networks. Modern computer vision unlocks them — shelf monitoring, footfall analytics, PPE compliance, queue management, headcount. All on existing cameras, processed on-prem. No new hardware in most cases.",
    "cta1": "Get a free site survey",
    "cta2": "See Praxate",
    "cta2_href": "/products/praxate/",
    "stat1_num": "On-prem",
    "stat1_lbl": "Video stays in your building",
    "stat2_num": "RTSP",
    "stat2_lbl": "Works on existing IP cams",
    "stat3_num": "Live",
    "stat3_lbl": "Alerts in seconds",
    "stat4_num": "ROI",
    "stat4_lbl": "Typically &lt; 6 months",
    "why_label": "Who this is for",
    "why_h2": "Retailers and warehouses with <em>15+ cameras</em> per site, getting zero AI value from them.",
    "why_intro": "If you run more than 15 CCTV cameras per site, you have an unrealised computer vision opportunity. Stockout detection. Queue management. Footfall analytics. PPE compliance. Each one is shippable today, each one earns its keep, none of them require new hardware in most cases.",
    "pain_points": [
        "Retail floors where popular SKUs go out of stock at 11am and nobody notices until the 4pm audit walk",
        "Checkout queues building silently as customers walk out without buying — invisible until POS data drops",
        "Warehouses where PPE compliance is checked by a supervisor walk-around — inconsistent at best, no audit trail at worst",
        "Stores spending on marketing campaigns that they can't tie back to footfall lift because nobody counts walk-ins",
        "Warehouses with after-hours security incidents discovered only on the morning review of footage",
        "Brand teams arguing about endcap effectiveness without a single data point about actual dwell time",
    ],
    "what_h2": "Computer vision use cases that <em>actually pay back</em>.",
    "what_intro": "We build computer vision deployments through both custom services and Praxate (our own AI-on-CCTV product). The capabilities below are what we ship in production — not lab demos.",
    "capabilities": [
        ("Shelf monitoring &amp; stockout alerts", "Cameras pointed at shelves continuously assess empty or low slots. Real-time alerts to floor staff. Aggregated trend dashboards by SKU, store, time-of-day."),
        ("Footfall counting &amp; demographics", "Entry-camera counts people in / out, with rough demographic estimation. Conversion rate = transactions / footfall. Campaign measurement."),
        ("Queue management at checkout", "Real-time queue length detection. Alerts when queue exceeds threshold. Aggregated data for staff scheduling."),
        ("PPE compliance for warehouses", "Helmet, vest, mask, glove detection in PPE-required zones. Non-compliance events logged with timestamp and clip. Audit trail for safety regulators and insurers."),
        ("Headcount &amp; zone occupancy", "Real-time headcount by zone. Heatmaps of foot traffic. Safety-capacity compliance. Productivity-zone occupancy."),
        ("After-hours intrusion alerts", "Zones + time windows defined. Person detected outside permitted hours? WhatsApp alert in seconds with video clip attached."),
    ],
    "approach_label": "How we deploy",
    "approach_h2": "Site survey first. <em>Honest read</em> on what your cameras will do.",
    "approach_left_h3": "Free survey before commitment",
    "approach_left_p": "We audit your existing cameras — angles, resolution, network access. Tell you which feeds will work for which use cases, which need repositioning, and which need replacing. Honest answer, before you commit to anything.",
    "approach_right_h3": "Pilot on one zone first",
    "approach_right_p": "Start with one store or one warehouse zone. Run for 30 days. Measure the impact. Then scale. The cost of a botched fleet-wide rollout is your operations broken across multiple sites. Pilot first, always.",
    "chips_h2": "Where we deploy.",
    "chips": ["Supermarkets &amp; grocery", "Apparel chains", "Electronics &amp; appliances", "QSR &amp; restaurant chains", "Pharmacy chains", "Furniture &amp; home", "Footwear &amp; accessories", "Warehouses &amp; FCs", "Cold chain &amp; pharma logistics", "Distribution centres", "Beauty &amp; cosmetics", "Specialty retail"],
    "faq": [
        ("Will the AI run on our existing CCTV cameras?", "In 95% of cases yes. Standard IP cameras supporting RTSP — the default for any modern Indian CCTV install — work for most use cases. We do a free site survey to confirm which feeds will work and which need repositioning."),
        ("Does video go to the cloud?", "No, by default. We process video on-prem on a small appliance at your site. Only structured events (alerts, attendance, headcount) sync to dashboards. This addresses both bandwidth costs and privacy concerns common in Indian retail / warehouse deployments."),
        ("How much does deployment cost?", "Per-site: ₹1.5L–₹4L for the on-prem appliance, plus per-camera-per-month software typically ₹500–₹2,500. ROI for shelf monitoring and queue management is usually under 6 months for mid-format retail."),
        ("Can you also do AI-based theft detection?", "Yes — behaviour analytics for suspicious patterns + self-checkout monitoring for scan-mismatch detection. Important caveat: system flags should triage to trained loss-prevention staff, not act as automatic accusations. Privacy by design matters here."),
        ("What about Praxate?", "Praxate is our productised AI-on-CCTV platform for workforce intelligence (attendance, headcount, PPE, intrusion). For retail-specific use cases like shelf monitoring, we typically build a custom layer alongside Praxate. See the Praxate guide for the product overview."),
    ],
    "final_cta_h2": "Cameras you already own, doing <em>more</em>.",
    "final_cta_p": "Free site survey to identify the use cases that fit your setup. No commitment. We tell you honestly which CCTV feeds will work and what would need new hardware.",
    "cta_wa": "https://wa.me/918897599624?text=Hi%2C%20I%27d%20like%20a%20site%20survey%20for%20AI%20on%20CCTV.",
    "related": [
        {"href": "/products/praxate/", "ttl": "Praxate", "desc": "Our AI workforce intelligence product — face attendance, PPE, intrusion."},
        {"href": "/blog/computer-vision-use-cases-retail-india/", "ttl": "CV in retail (blog)", "desc": "Eight specific computer vision use cases with ROI math."},
        {"href": "/industries/retail/", "ttl": "Retail Software", "desc": "POS, OMS, D2C, omnichannel — broader retail practice."},
    ],
})

# ═══════════════════════════════════════════════════════════════════
# 8. AI for Manufacturing Quality
# ═══════════════════════════════════════════════════════════════════
PAGES.append({
    "slug": "ai-for-manufacturing-quality-control",
    "service_name": "AI for Manufacturing Quality Control",
    "service_type": "Computer Vision and AI for Manufacturing QC",
    "title": "AI for Manufacturing Quality Control in India — Defect Detection, OCR — XServ Labs",
    "description": "Computer vision and AI for Indian manufacturing quality control — defect detection, surface inspection, OCR on production tags, PPE compliance, predictive maintenance. Production-grade, on-prem capable.",
    "keywords": "ai for manufacturing quality control india, defect detection ai india, computer vision manufacturing india, automated quality inspection, manufacturing ai hyderabad",
    "crumb": "AI for Manufacturing Quality",
    "eyebrow": "AI · Manufacturing",
    "h1": "AI quality control that catches what the <em>tired inspector</em> misses.",
    "lede": "Manual visual inspection at the end of a production line has a known failure rate — and the failure rate is higher in the third shift than the first. AI vision systems hold the line consistently, log every check, and surface defect patterns that humans miss across thousands of units.",
    "cta1": "Start a project",
    "cta2": "Read the AI guide",
    "cta2_href": "/services/ai-ml-development/",
    "stat1_num": "On-line",
    "stat1_lbl": "Or end-of-line",
    "stat2_num": "Edge",
    "stat2_lbl": "Runs on-prem",
    "stat3_num": "OCR",
    "stat3_lbl": "Production tags &amp; labels",
    "stat4_num": "Audit",
    "stat4_lbl": "Every inspection logged",
    "why_label": "Who this is for",
    "why_h2": "Manufacturers tired of QC variance between shifts and inspectors.",
    "why_intro": "Manual visual QC is good. Manual visual QC at 11pm in the third shift, after the lead inspector has called in sick, with two trainees on the line — that is where defects ship. AI vision systems hold a consistent standard 24/7, log every check for audit, and flag patterns no human could see across thousands of units.",
    "pain_points": [
        "Defect rates spiking on certain shifts and nobody knowing why",
        "Customer complaints about issues that QC supposedly caught — but the paper records don't show it clearly",
        "Inspectors burning out from end-of-line visual checks that all look alike after hour 6",
        "Production tags and labels printed wrong, caught only when the customer rejects the shipment",
        "PPE compliance on the line tracked by supervisor walk-around — inconsistent at best",
        "Machine downtime that could have been prevented with earlier signal — but the signal was never captured",
    ],
    "what_h2": "AI vision applications shipped on <em>real factory floors</em>.",
    "what_intro": "We build manufacturing AI that runs on-prem, integrates with your existing line, and produces results inspectors trust. The patterns below are deployed, not lab demos.",
    "capabilities": [
        ("Surface defect detection", "Scratches, dents, discolouration, contamination, missing components. Trained on your product's specific defect taxonomy. Configurable accept/reject thresholds."),
        ("OCR on production tags", "Read printed batch numbers, expiry dates, lot codes, serial numbers on labels and packaging. Validate against the production order. Catch print errors before they leave the line."),
        ("Pre-shipment label verification", "Final-station verification of carton labels, shipping marks, regulatory marks. Catch wrong-label-on-right-product errors that recall investigations later."),
        ("PPE compliance via existing CCTV", "Helmet, vest, mask detection in production zones. Non-compliance events logged with timestamp and clip. Audit trail for safety regulators and your insurance renewals."),
        ("Predictive maintenance signal", "Machine sensor data + ML to predict failures before they cause line stoppage. We have cut unplanned downtime by 30–50% in pilot deployments."),
        ("Headcount &amp; productivity zones", "Track shift attendance, zone-based productivity, dwell time in workstations — useful for capacity planning and operational improvement."),
    ],
    "approach_label": "How we deploy",
    "approach_h2": "PoC fast. Production deliberately.",
    "approach_left_h3": "2–4 week proof of concept",
    "approach_left_p": "We deploy a PoC on a sample of your defects within 2–4 weeks of project start. You see the actual model performance on your actual products before committing to production deployment. If accuracy is not good enough, you have not committed to the production phase yet.",
    "approach_right_h3": "Production-grade integration",
    "approach_right_p": "Production deployment includes line integration (camera mounts, lighting, PLC tie-in), operator UI on shop-floor tablets, escalation workflow to QC supervisors, audit logging, and ongoing model retraining as new defect types emerge. We do not ship PoCs as production systems.",
    "chips_h2": "Manufacturing sub-sectors we have shipped for.",
    "chips": ["Automotive components", "Pharma manufacturing", "Textile &amp; fabric", "Food &amp; FMCG packaging", "Electronics assembly", "Metal fabrication", "Plastics &amp; injection moulding", "Cement &amp; building materials", "Industrial machinery", "Glass &amp; ceramics", "Chemicals", "Printing &amp; packaging"],
    "faq": [
        ("How long until we see results?", "Working PoC on your defect data in 2–4 weeks. Production deployment with line integration, operator UI, and audit logging adds 6–12 weeks depending on integration complexity. We do not believe in 6-month research projects with nothing to show for them."),
        ("Can the AI run on-prem without cloud?", "Yes — and we usually deploy that way for manufacturing. Models run on a small appliance at your site. No video or proprietary product data leaves the factory floor."),
        ("What if our defect types change over time?", "Models can be retrained as new defect types emerge. We typically include quarterly retraining cycles in the support retainer. Operators can flag false positives / false negatives in the UI, which feed back into the retraining set."),
        ("How accurate is AI defect detection compared to human inspectors?", "On well-controlled lines with consistent product appearance, AI typically achieves 95-99% recall (catching real defects) and reduces false positives over time. The bigger win is consistency — AI does not get tired, distracted, or off-shift."),
        ("Will it integrate with our existing MES or ERP?", "Yes — defect events feed into your MES (Wonderware, Ignition, custom) and ERP (SAP, Oracle, custom). Bi-directional integration so production data feeds the model and the model feeds back to traceability records."),
    ],
    "final_cta_h2": "Quality issues you <em>cannot quite</em> get on top of?",
    "final_cta_p": "30-minute call. We will tell you honestly whether AI vision is the right answer or whether process changes would solve more cheaply.",
    "cta_wa": "https://wa.me/918897599624?text=Hi%2C%20I%27d%20like%20to%20discuss%20AI%20for%20manufacturing%20quality.",
    "related": [
        {"href": "/services/ai-ml-development/", "ttl": "AI &amp; ML Services", "desc": "The full AI/ML guide — capabilities, process, frameworks."},
        {"href": "/industries/manufacturing/", "ttl": "Manufacturing Software", "desc": "ERP, MES, shop-floor, AI — full manufacturing practice."},
        {"href": "/services/erp-for-pharma-manufacturers/", "ttl": "ERP for Pharma", "desc": "Where AI defect detection integrates with batch traceability."},
    ],
})

# ═══════════════════════════════════════════════════════════════════
# 9. Cloud DevOps for Fintech
# ═══════════════════════════════════════════════════════════════════
PAGES.append({
    "slug": "cloud-devops-for-fintech",
    "service_name": "Cloud and DevOps for Indian Fintech",
    "service_type": "Cloud Architecture, DevOps, SRE for Fintech",
    "title": "Cloud DevOps for Indian Fintech — RBI-Aligned Architecture — XServ Labs",
    "description": "Cloud architecture and DevOps for Indian fintech — RBI-aligned infrastructure, India data residency, immutable audit trails, SOC 2 / ISO readiness, 24/7 SRE retainers. Built for regulated environments.",
    "keywords": "cloud devops for fintech india, rbi compliant infrastructure, fintech aws architecture india, fintech devops services, india data residency aws, fintech soc 2 ready",
    "crumb": "Cloud DevOps for Fintech",
    "eyebrow": "Cloud · DevOps · Fintech",
    "h1": "Fintech infrastructure that <em>holds up to regulators</em>.",
    "lede": "Indian fintech has unique infrastructure constraints — RBI guidelines, India data residency, audit-trail immutability, regulator notification timelines. Generic DevOps doesn't cover these. We build cloud architecture and DevOps practices designed for regulated environments from day one.",
    "cta1": "Start a project",
    "cta2": "Read the DevOps guide",
    "cta2_href": "/services/cloud-devops/",
    "stat1_num": "India",
    "stat1_lbl": "Data residency default",
    "stat2_num": "Immutable",
    "stat2_lbl": "Audit logs day one",
    "stat3_num": "SOC 2",
    "stat3_lbl": "+ ISO ready",
    "stat4_num": "24/7",
    "stat4_lbl": "SRE retainer available",
    "why_label": "Who this is for",
    "why_h2": "Fintech startups that <em>cannot afford</em> to retrofit compliance.",
    "why_intro": "Indian fintech infrastructure built without compliance in mind always becomes the project's largest technical debt. We have inherited those rebuilds. Doing it right at week one is 10x cheaper than retrofitting after the first audit.",
    "pain_points": [
        "Fintechs storing payment data in non-India regions because nobody mapped the data flow before shipping",
        "Audit logs that are not truly immutable — admins can delete them, which fails most regulator inspections",
        "Secrets in env vars and CI/CD configs because the team never set up Secrets Manager properly",
        "Production incidents handled ad-hoc because there is no on-call rotation, no PagerDuty, no runbooks",
        "Cloud bills creeping every quarter because nobody is running FinOps reviews",
        "Companies 90 days from a SOC 2 audit with no clear plan for control implementation",
    ],
    "what_h2": "Compliance-first patterns for <em>fintech infrastructure</em>.",
    "what_intro": "Everything below is what we set up week one for new fintech engagements — or retrofit for companies that built without it. Each one solves a regulatory or audit problem that becomes expensive later.",
    "capabilities": [
        ("India-region cloud architecture", "AWS / Azure / GCP in Indian regions (Mumbai, Hyderabad, Chennai). Multi-AZ baseline. India-to-India DR. Payment data never accidentally routes through non-India regions."),
        ("Immutable audit logging", "CloudTrail + S3 with object lock. Or stream to Splunk/Elastic with write-only access. Tamper-evident, regulator-acceptable, with the retention period your regulator mandates."),
        ("Secrets management done right", "AWS Secrets Manager / Vault / Azure Key Vault. Pre-commit hooks to block accidental commits. Quarterly rotation. Audit logging on every access."),
        ("CI/CD with security gates", "Snyk / Trivy / Semgrep / tfsec all in the pipeline. Each gate fails the build hard. Manual approval gates before production. Canary rollouts with automated rollback."),
        ("Network segmentation", "DMZ, application, data, payment, admin zones. Cross-zone traffic only via explicit allowlists. PCI-DSS-grade isolation for card-data systems."),
        ("SOC 2 / ISO 27001 readiness", "Gap assessment, policy library, control implementation, evidence pipelines, employee training, audit liaison. Most clients audit-ready in 8–16 weeks."),
    ],
    "approach_label": "How we engage",
    "approach_h2": "Two starting points, picked by where you are.",
    "approach_left_h3": "Greenfield: week-one foundation",
    "approach_left_p": "Pre-launch fintech: we set up the full foundation in 2 weeks — India-region cloud, network segmentation, Terraform-managed infra, CI/CD with security gates, secrets management, immutable audit logs, observability stack. You launch on infrastructure that will pass audit. We then stay on as managed SRE.",
    "approach_right_h3": "Existing fintech: gap assessment first",
    "approach_right_p": "Live fintech with debt: we run a 1-week security and infrastructure audit. Identify the gaps that matter to regulators and the gaps that matter to operations. Prioritise by risk. Then we either remediate ourselves or hand the plan to your team.",
    "chips_h2": "Fintech sub-categories we have worked with.",
    "chips": ["Neo-banking", "Lending &amp; BNPL", "Wealth management", "Insurance tech", "Payment platforms", "B2B SaaS for finance", "Trading platforms", "RegTech", "Banking-as-a-Service", "Microfinance", "Cross-border payments", "Embedded finance"],
    "faq": [
        ("How do we satisfy RBI data residency requirements?", "By default, all payment data stays in Indian regions (AWS Mumbai/Hyderabad, Azure India, GCP Mumbai). Non-payment workloads have more flexibility. Critically, we map and verify data flows so nothing routes through non-India regions unintentionally — which is where most violations happen."),
        ("What audit logging is regulator-acceptable?", "Immutable, tamper-evident logs with the retention period your regulator mandates (usually 5+ years for payment data). CloudTrail to S3 with object lock is the standard pattern on AWS. SIEM aggregation on top for searchability and detection."),
        ("How long does SOC 2 / ISO 27001 readiness take?", "Typically 8–16 weeks from program start to audit-ready, depending on starting point. We use compliance automation tools (Drata, Vanta, Sprinto) where they make sense, custom evidence pipelines where they don't."),
        ("Do you offer 24/7 incident response?", "Yes — managed SRE retainers with 24/7 PagerDuty coverage. Defined SLAs by severity. Runbooks for top incident types. Quarterly drills. We become your effective on-call so your engineers can ship."),
        ("Can you help with RBI Cybersecurity Framework requirements?", "Yes — we have worked with NBFCs and payment companies through RBI cybersecurity reviews. Practical control implementation, policy library, evidence collection, and audit liaison."),
    ],
    "final_cta_h2": "Building Indian fintech and want infrastructure that <em>holds up to inspection</em>?",
    "final_cta_p": "30-minute call. We will tell you honestly where your biggest compliance gaps are and what fixing them realistically takes.",
    "cta_wa": "https://wa.me/918897599624?text=Hi%2C%20I%27d%20like%20to%20discuss%20cloud%20devops%20for%20fintech.",
    "related": [
        {"href": "/services/cloud-devops/", "ttl": "Cloud &amp; DevOps", "desc": "The full DevOps guide — clouds, K8s, CI/CD, SRE."},
        {"href": "/services/cybersecurity/", "ttl": "Cybersecurity", "desc": "Pentests, SOC 2 / ISO readiness, ongoing monitoring."},
        {"href": "/blog/devops-for-indian-fintech/", "ttl": "Fintech DevOps playbook", "desc": "Full compliance-first playbook with practical patterns."},
    ],
})

# ═══════════════════════════════════════════════════════════════════
# 10. Cybersecurity for SaaS Startups
# ═══════════════════════════════════════════════════════════════════
PAGES.append({
    "slug": "cybersecurity-for-saas-startups",
    "service_name": "Cybersecurity for SaaS Startups",
    "service_type": "Cybersecurity Services for SaaS Companies",
    "title": "Cybersecurity for SaaS Startups in India — Pentests, SOC 2 — XServ Labs",
    "description": "Cybersecurity for Indian SaaS startups — penetration testing, secure code review, SOC 2 readiness, vCISO advisory, ongoing monitoring. Built for the security expectations enterprise customers will demand.",
    "keywords": "cybersecurity for saas startups india, pentest for saas india, soc 2 india startup, vciso services india, saas security audit india",
    "crumb": "Cybersecurity for SaaS Startups",
    "eyebrow": "Cybersecurity · SaaS",
    "h1": "Security that unblocks <em>enterprise deals</em> — and stops the breach before it's a breach.",
    "lede": "B2B SaaS hits a wall at the first enterprise sales cycle. Security questionnaires, SOC 2 requirements, pentests on demand, vendor reviews. Done reactively, this kills deals. Done proactively, it accelerates them. Most Indian SaaS startups need a partner who handles this as a programme, not as one-off audits.",
    "cta1": "Get a security scoping call",
    "cta2": "Read the cybersecurity guide",
    "cta2_href": "/services/cybersecurity/",
    "stat1_num": "OWASP",
    "stat1_lbl": "Methodology standard",
    "stat2_num": "SOC 2",
    "stat2_lbl": "Type I in 8–16w",
    "stat3_num": "NDA",
    "stat3_lbl": "Before first call",
    "stat4_num": "vCISO",
    "stat4_lbl": "Retainers from ₹1L/mo",
    "why_label": "Who this is for",
    "why_h2": "B2B SaaS startups whose <em>enterprise deals</em> are stalling on security review.",
    "why_intro": "If your sales team is closing on product but stalling on security questionnaires, the gap isn't your product — it's your security posture. We help SaaS startups close that gap fast, with the artefacts enterprise procurement actually wants to see.",
    "pain_points": [
        "Enterprise prospects asking for SOC 2 reports you don't have — and the deal going cold",
        "Security questionnaires from procurement that take your CTO three days to fill out",
        "DPAs and security addendums getting redlined endlessly because you don't have standard answers",
        "Engineering team patching dependencies reactively, not on a schedule, leaving exploitable windows open",
        "No clear security owner — the founder is doing it on top of everything else",
        "Audit logs that exist in 6 different places, none of them queryable, none of them retained correctly",
    ],
    "what_h2": "Cybersecurity work that <em>unblocks revenue</em>, not just compliance theatre.",
    "what_intro": "Every SaaS startup has a security backlog. The trick is knowing which items actually block deals or matter to attackers — and doing those first. We focus on the work that creates real risk reduction or real revenue unblock.",
    "capabilities": [
        ("Penetration testing", "Web app, API, mobile, cloud infra. OWASP methodology. Findings ranked by exploitability, not just CVSS. Business-context impact, not generic risk language."),
        ("SOC 2 readiness program", "Gap assessment, policy library, technical controls, evidence pipelines, employee training, audit liaison. Most startups Type I audit-ready in 8–16 weeks."),
        ("vCISO retainer", "Fractional CISO — 10–20 hours/month. Security strategy, customer security reviews, vendor risk, incident response leadership. Right for startups not ready for a full-time hire."),
        ("Secure code review", "Manual review by engineers who write production code. Auth flows, business logic, secrets handling, dependency risk. Findings come with code-level fix suggestions."),
        ("Customer security review acceleration", "Pre-built answers to common security questionnaire questions. Reduce the response time from 3 days to 30 minutes. Speeds enterprise deal cycles."),
        ("Continuous monitoring", "Managed SIEM, vulnerability scanning, alerting, incident response. Either open-source stack (Wazuh) or paid platforms (CrowdStrike, Wiz, Datadog) depending on budget and scale."),
    ],
    "approach_label": "How we engage with SaaS startups",
    "approach_h2": "Programme-based, not one-off audits.",
    "approach_left_h3": "Continuous, not periodic",
    "approach_left_p": "One pentest a year is the legacy model. Modern SaaS ships weekly — attack surface changes weekly. We offer continuous engagement: pentest cycles, vulnerability scanning, ongoing security review, vCISO retainer. Costs less than the annual-pentest-plus-emergency-response pattern most startups fall into.",
    "approach_right_h3": "Revenue-driven prioritisation",
    "approach_right_p": "We sort security backlog by what unblocks revenue first. SOC 2 to close that ₹2 crore deal? Top of the list. Security headers? Important but later. The security work that gets done is the work that creates real business value, not the work that fills the longest report.",
    "chips_h2": "SaaS categories we have worked with.",
    "chips": ["B2B horizontal SaaS", "Vertical SaaS", "Developer tools", "Fintech SaaS", "HR tech", "Logistics SaaS", "Marketing tech", "Sales tech", "Healthcare SaaS", "EdTech", "Marketplace platforms", "API-first products"],
    "faq": [
        ("How much does a SaaS pentest cost?", "Realistic ranges from a competent India-based firm: single web app grey-box ₹1.5L–₹3.5L, web + API + multiple roles ₹2.5L–₹5L, full stack (web + API + mobile + cloud) ₹6L–₹12L. We provide fixed quotes after a scoping call."),
        ("What is included in a SOC 2 readiness program?", "Gap assessment against SOC 2 Trust Services Criteria, policy library implementation, technical control deployment (audit logs, access reviews, vulnerability management), evidence pipeline setup, employee training, audit firm coordination. Type I in 8–16 weeks, Type II adds 6 more months of evidence collection."),
        ("Do we need a vCISO, or can our CTO handle security?", "Depends on stage. Under 10 engineers, your CTO can probably handle it with our part-time support. 10–30 engineers, a vCISO retainer relieves the CTO of security-program ownership. 30+ engineers shipping enterprise SaaS, consider a full-time security engineer."),
        ("How quickly can you start?", "Pentests: typically within 1 week of scoping call. SOC 2 readiness: kickoff within 2 weeks. vCISO retainer: starting within 1 week. Emergency incident response: same day, talk to us."),
        ("Do you sign NDAs and DPAs?", "Always. NDA before any technical conversation. DPA, custom security agreements, and SLA contracts as standard for SaaS engagements. We have signed these for hundreds of clients across India, US, UK, UAE."),
    ],
    "final_cta_h2": "SaaS startup stuck at enterprise security review?",
    "final_cta_p": "30-minute scoping call. We will tell you the 3 highest-leverage security moves for your specific stage — the ones that unblock revenue, not the ones that pad reports.",
    "cta_wa": "https://wa.me/918897599624?text=Hi%2C%20I%27d%20like%20to%20discuss%20cybersecurity%20for%20a%20SaaS%20startup.",
    "related": [
        {"href": "/services/cybersecurity/", "ttl": "Cybersecurity Services", "desc": "Full cybersecurity practice — pentests, audits, compliance, monitoring."},
        {"href": "/services/cloud-devops/", "ttl": "Cloud &amp; DevOps", "desc": "Secure-by-default infrastructure built alongside the security program."},
        {"href": "/blog/penetration-testing-checklist-india-saas/", "ttl": "Pentest checklist", "desc": "Practical guide to scoping a pentest and reading the report."},
    ],
})
